services:
  spark:
    image: apache/spark:4.0.0
    container_name: spark
    ports:
      - "8080:8080"
    volumes:
      - ../data:/data
      - ../spark_jobs:/spark_jobs
      - ../pipeline:/pipeline
    command: tail -f /dev/null

  airflow:
    build: .
    image: airflow-custom:latest
    container_name: airflow
    depends_on:
      spark:
        condition: service_started
    env_file:
      - ../.env
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "${AIRFLOW_ADMIN_USER}:admin"
      PYTHONPATH: "/opt/airflow"
      PYTHONUNBUFFERED: "1"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../spark_jobs:/opt/airflow/spark_jobs
      - ../pipeline:/opt/airflow/pipeline
      - ../monitoring:/opt/airflow/monitoring
      - ../data:/data
    ports:
      - "8081:8080"
    command: >
      bash -c "echo '{\"${AIRFLOW_ADMIN_USER}\": \"${AIRFLOW_ADMIN_PASSWORD}\"}' > /opt/airflow/simple_auth_manager_passwords.json.generated && exec airflow standalone"

  streamlit:
    image: airflow-custom:latest
    container_name: streamlit
    depends_on:
      airflow:
        condition: service_started
    env_file:
      - ../.env
    environment:
      PYTHONPATH: "/app"
      AIRFLOW_API_URL: "http://airflow:8080"
      PYTHONUNBUFFERED: "1"
    volumes:
      - ../dashboard:/app
      - ../pipeline:/app/pipeline
      - ../data:/data
    ports:
      - "8501:8501"
    entrypoint: ["streamlit"]
    command: ["run", "/app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]